### PR TITLE
allow passing -api parameters to exiftool

### PR DESCRIPTION
**Pull request by Blesmol**

### CODE REVIEW

**Comment by barasher** [comment]
Hi, thanks for the PR.
Is it possible to add an integration test that use this option and that would be used as a non regression test ?

**Comment by barasher** [comment]
In fact, when I add a new option, I try to check if it effectively does what it is supposed to do.
Since it is not possible to check every API parameter values, I would just check one. I would check on a specific file that a specific field is extracted with a specific API parameter value and that it isn't without the API parameter.
It would also indirectly check that :
- the API parameter is still compatible with the JSON serialization
- there is no breaking change on exiftool with its API parameter

**Comment by barasher** [comment]
Have a look at the `TestExtractAllBinaryMetadata` test:
- it checks extraction without the exiftool parameter (the field X is not extracted)
- it check extraction with the exiftool parameter (the field X is now extracted)

**Comment by Blesmol** [comment]
Sorry for the delay, currently only able to check this every couple of days.

Some open questions on my side:
* You're bringing `TestExtractAllBinaryMetadata` as example. But isn't that a regression test, although initially you were mentioning non-regression tests? How do you differentiate here between both? In general I can add something like this. Need to see whether I can provide a binary testfile that is as small as possible.
* Which JSON serialization? Happy to test this as well, but wasn't aware that there is some JSON serialization anywhere.
* The part about "no breaking change on exiftool with its API parameter" I did not understand...

**Comment by barasher** [comment]
> **You're bringing `TestExtractAllBinaryMetadata` as example. But isn't that a regression test, although initially you were mentioning non-regression tests? How do you differentiate here between both? In general I can add something like this. Need to see whether I can provide a binary testfile that is as small as possible.**

The idea of this test is to check that the `Api` function is concretely working. The best way to test it is to try it with a concrete sample that returns something with the `Api` settings that exiftools does not return without it. It proves that it works at least in one use-case.

Here is a sample with an existing file in the repository :
```
barasher@linux:~/go/src/github.com/barasher/go-exiftool/testdata$ exiftool 20190404_131804.jpg | grep 'File Block Size'

barasher@linux:~/go/src/github.com/barasher/go-exiftool/testdata$ exiftool -api systemtags 20190404_131804.jpg | grep 'File Block Size'
File Block Size                 : 4096
```

I call it a non regression test because if anything changes with the exiftool's `-api` parameter (for instance, `-api` is renamed `-api_parameter`, this unit-test should not work anymore. In `go-exiftool`'s point of view, if something that used to work does not work anymore, it is a regression. The test checks that there is not any regression concerning the parameter.

I think that we agree and that it is just a vocabulary issue :) 

-----------

> **Which JSON serialization? Happy to test this as well, but wasn't aware that there is some JSON serialization anywhere.**

`go-exiftool` uses exiftools `-j` parameter that formats metadata in JSON:

```
barasher@linux:~/go/src/github.com/barasher/go-exiftool/testdata$ exiftool 20190404_131804.jpg
Orientation                     : Rotate 90 CW
X Resolution                    : 72
Y Resolution                    : 72

barasher@linux:~/go/src/github.com/barasher/go-exiftool/testdata$ exiftool -j 20190404_131804.jpg
[{
  "Orientation": "Rotate 90 CW",
  "XResolution": 72,
  "YResolution": 72
}]
```

I feared that `exiftool`s `-api` parameter could not be compatible with the `-j` parameter but it seems that it's ok:

```
barasher@linux:~/go/src/github.com/barasher/go-exiftool/testdata$ exiftool -j -api systemtags 20190404_131804.jpg 
[{
  "FileBlockSize": 4096
}]

```

**Comment by barasher** [comment]
@Blesmol, are you still OK to work on this PR ?

**Comment by Blesmol** [comment]
@barasher Yep. Sorry for the delay, Newborn child in the family takes up a lot of time :) Will see that I find time within the next couple of days (after getting some proper sleep)

**Comment by Blesmol** [comment]
> I think that we agree and that it is just a vocabulary issue :)

I agree :) What you described there I would call a regression test. The "non regression" part was what was confusing me in the wording.

I've added now another unittest that tests an actual `api` setting and shows that the parameter has an impact. Would that be sufficient? If I understood you correctly, then for the JSON part no additional tests are required at the moment?

**Comment by barasher** [comment]
Congratulations for your newborn baby !
Thanks for the PR, I'll certainly review and merge it this weekend !

**Review by barasher — APPROVED** [review]

**Pull request merged**
