### PR TITLE
Adding the PrintGroupNames option

### PR DESCRIPTION
**Pull request by agorman**
I'd like to use the -G option so I'd like to add the `PrintGroupNames` method.

Thanks!

### CODE REVIEW

**Comment by agorman** [comment]
Bump. Don't want to bother you but hoping you take a look if you have a second.

**Comment by barasher** [comment]
Hello.
I'm sorry but I'm on holidays, without any computer, I'll be back in one
week.
Sincerely
Arnaud

**Comment by agorman** [comment]
@barasher thank you for the response. Enjoy your holiday. Talk when you get back.

**Comment by agorman** [comment]
@barasher I believe you should be back now. If so can you take a look. If not then feel free to ignore this until you return.

Thanks!

**Comment by barasher** [comment]
Hi @agorman !
Once again sorry for the delay.

There's a little thing that bothers me with this implementation.
You've chosen to use the `-G` option that is a shortcut to `-G0`. It fits your use-case, but I think that it isn't generic enough : some other people might prefer the `-G1` option for instance.

What about adding another parameter that specifies which "number" to use ?

Sincerely,
Arnaud

**Comment by agorman** [comment]
Great point. Because the `-G` option allows for multiple group number (`-G[*NUM*][:*NUM*...]`) I can change the `PrintGroupNames` function to take a string. That way a `0` could be passed or multiple group numbers like `3:1`.

What do you think?

**Comment by agorman** [comment]
Alternatively I could change `PrintGroupNames` to take `...int`. That way if nothing was passed I could assume `0`. Otherwise I could create the group names string based on the passed ints.

**Comment by barasher** [comment]
> Great point. Because the `-G` option allows for multiple group number (`-G[*NUM*][:*NUM*...]`) I can change the `PrintGroupNames` function to take a string. That way a `0` could be passed or multiple group numbers like `3:1`.
> 
> What do you think?

I think that's the best option ! A string parameter would be great.

**Comment by barasher** [comment]
It seems great !

**Comment by barasher** [comment]
I've updated exiftool and all tests are passing

**Comment by barasher** [comment]
Once more, thanks for the PR !
Released in v1.10.0

**Pull request merged**
